### PR TITLE
Document multiple queries in a COUNT request

### PR DESCRIPTION
**Pull request by Giszmo**

### CODE REVIEW

**Comment by staab** [comment]
I believe @fiatjaf preferred to remove the positional arguments. If someone wants multiple counts, they can send multiple COUNT requests.

**Comment by Giszmo** [comment]
Uhm ... what? Then remove the multiple queries from the request maybe? Or define what the relay is supposed to do with those. As it stands, the client may send a thousand queries and the relay may aggregate the counts, ignore all but the first or whatever.

**Comment by staab** [comment]
Are you referring to `["COUNT", <subscription_id>, <filters JSON>...]`? That works the same way as REQ, and returns a single count with the filters OR'd together. That could definitely be clarified though if you want to update the PR.

**Comment by Giszmo** [comment]
Nah, I'm good

**Pull request closed without merging**
