### PR TITLE
NUD: Nostr Unofficial Documents

### PR DESCRIPTION
**Pull request by SilberWitch**
This is a continuance/adaptation of the original @fiatjaf proposal for NUDs as [NIP-71](https://github.com/nostr-protocol/nips/blob/nuds/71.md).

The concept is meant to reduce the need for everyone to maintain varying [Nostr event lists](https://wikistr.com/nostr-event-register*fd208ee8c8f283780a9552896e4823cc9dc6bfd442063889577106940fd927c1) and to have different levels of publication (NIP _and_ NUD, or _only_ NUD).

This would allow us to 
- filter relays for Nostr specs, 
- embed spec references in other documents, using nostr addresses, such as in product documentation,
- auto-assemble lists from filter results, in varying formats, or with sorting by field,
- open up new use cases for navigating and expanding the specification base, and 
- add acceptance-test content or other auxiliary information/instructions
 
all without eliminating the primary/leading role of the NIP-repo as a "standard spec set" or altering/ossifying the source specification content.

### CODE REVIEW

**Comment by SilberWitch** [comment]
Some of the readme stuff is wrong. I'll correct that, later.

**Comment by fiatjaf** [comment]
The only difference between my proposal and this is the introduction of the "gherkin" stuff? Or what is it?

I don't know if I like my own proposal anymore, I think maybe it's better if people do the blossom route and just maintain a spec _anywhere_ and we link to it from this repo in order to reserve event kinds.

**Comment by SilberWitch** [comment]
This is about the tag metadata, mostly, and the gherkin. The prose specs stay where they are.

I just left the spec stuff in the proposal because it was in the original, but it's redundant to the description field. I'd be fine, with taking it out.

**Comment by SilberWitch** [comment]
I have a specific use case for putting the metadata in events, but I wanted to run it by you, before I start producing the events, because of the tag selection and the data structure.

**Comment by SilberWitch** [comment]
Yeah, I know. 😂 This is advanced spec-ing.

We're going to be handling them from our clients. Just trying to do it with events, instead of going straight to a database, so that someone else can also make use of them.

I'm okay with it just being us, though. Doesn't need to be a NIP. NUDs can just be a NUD.

**Comment by SilberWitch** [comment]
Michael suggested I split the metadata part from the gherkin part, into two events, and then link them together with a 30040, along with other docs. Like a superspec.

**Pull request closed without merging**
