### PR TITLE
Qualified tags

### PR DESCRIPTION
**Pull request by unclebob**
This is a proposal for Qualified Tags, that I believe will resolve the 'reply' ambiguities created by NIP-10 and also add needed flexibility as use-cases proliferate.

### CODE REVIEW

**Comment by unclebob** [comment]
I'm afraid we might run out of single letter tags.  Some folks have already used `r` for something.  We're going to keep having collisions like this if we don't broaden the definition of a tag.

**Comment by unclebob** [comment]
Hmm..  Can't delete emojis.  ;-)

**Comment by fiatjaf** [comment]
With regards to running out of letters, I think we won't. In fact I think we shoud just use `e` for events, `p` for pubkeys and `r` for any "reference" (i.e., anything that isn't an event or pubkey but you still want to index, like a URL or a name or a phone number).

**Comment by fiatjaf** [comment]
Now I've read the proposal and I think I understand the issue.

I don't like changing the tags with the qualifier because I don't like that relays are expected to index all tags (NIP-12, we should get rid of NIP-12). I think the solution should be either to add a marker to the tag arrays, like

```json
"tags": [
  ["e", "abcde...", "<relay url or empty string>", "root"],
  ["e", "abcde...", "<relay url or empty string>", "reply"]
]
```

This way current clients can just not parse these tags if they don't want and keep using their NIP-10 behavior.

Or we can add two new tags `"t"`, which is the same as `"e"` but indicates the root of the **t**hread, and `"d"` which is the same as `"e"` but indicates a **d**irect reply. All other `"e"` tags can be treated as mentions or references inside the text.

```json
"tags": [
  ["e", "abcde...", "<relay url or empty string>"],
  ["t", "abcde...", "<relay url or empty string>"],
  ["d", "abcde...", "<relay url or empty string>"],
  ["e", "abcde...", "<relay url or empty string>"]
]
```

I think we should keep the convention of using the single-letter tag names for stuff that means to be indexed and larger tag names for any other metadata.

I think we shouldn't worry about running out of letters. If that ever happens that will mean the protocol is very successful and we can start using larger tag names and relays will adapt, or use greek letters, I don't know. I honestly can't imagine so many letters being used.

**Comment by unclebob** [comment]
I think I like the "marker" idea best.  The backwards compatibility argument is convincing.  Clients can continue to use NIP-10 if they like.

**Comment by jb55** [comment]
> @fiatjaf says:
> ```json
> "tags": [
>   ["e", "abcde...", "<relay url or empty string>", "root"],
>   ["e", "abcde...", "<relay url or empty string>", "reply"]
> ]

fwiw this is exactly what I wad referring to by `adding these qualifiers to the tag's list of strings.`. This would be trivial to implement in damus. In addition to "root", "reply" we might also want "mention" for the case where it is mentioned in the content.

**Pull request closed without merging**
