### PR TITLE
delete NIP-22

### PR DESCRIPTION
**Pull request by fiatjaf**
because it is useless and no one cares about it.

### CODE REVIEW

**Comment by vitorpamplona** [comment]
I didn't even know those things existed.

**Comment by AsaiToshiya** [comment]
https://github.com/nostr-protocol/nips/blob/7822a8b12670312aff104ddc03066425882f739d/11.md?plain=1#L134-L136

These may also need to be delete.

**Comment by weex** [comment]
I'm not sure if we want to encourage people to bring old content to nostr but created_at would help decide between relays if you were looking to [archive old social media posts](https://blog.lopp.net/how-to-exit-x-to-social-network-sovereignty/) and didn't want to have run your own relay.

**Comment by fiatjaf** [comment]
There are already fields on NIP-11 describing what relay accept or not -- although I think this could and should be decided mostly manually anyway.

**Review by pablof7z — APPROVED** [review]

**Comment by AsaiToshiya** [comment]
Is NIP-22 a reusable number? Won't it be a problem like NIP-15 in the future?

**Pull request merged**
