### PR TITLE
Add P-tags and p-tags to NIP-22

### PR DESCRIPTION
**Pull request by pablof7z**
This is needed to pull comments a user should look at.

cc @vitorpamplona

### CODE REVIEW

**Comment by vitorpamplona** [comment]
Do we add `P` in addition to `p` for the root? I know many clients only find notifications by `p`. 🤔

**Comment by pablof7z** [comment]
Yeah, to keep it consistent if replying to the root both P and p point to the author

**Review by staab — APPROVED** [review]

**Comment by dtonon** [comment]
I'm a little confused about how a NIP-22 comment can support mentions (NIP-27). It seems that with the current specs is not possible. What am I missing?

**Comment by pablof7z** [comment]
> I'm a little confused about how a NIP-22 comment can support mentions (NIP-27). It seems that with the current specs is not possible. What am I missing?

Just a `p` tag? Could have a `mention` marker.

**Pull request merged**
