### PR TITLE
Add support for proxying AUTH

### PR DESCRIPTION
**Pull request by staab**
Related to https://github.com/nostr-protocol/nips/issues/1013

I drafted this to see what it would look like. I sort of want relay proxies, but they may come at too high a cost. NACK unless someone changes my mind.

### CODE REVIEW

**Comment by staab** [comment]
> Gotta figure out where to save the setting of what to proxy in each relay for the user.

That would be useful, but for now I was thinking the client would just make the decision.

**Comment by Yonle** [comment]
The new scheme `["AUTH", "<id>", "<url>"]` is really a weak approach to handle this problem. The relay at this point asks you who are you connected to, not the relay tells you who you connected to.

This does not make sense as proxy could spoof the `<url>` regardless of the value no matter the value does not match to the current established `host`.

**Comment by staab** [comment]
Yes, but the client would sign the spoofed value in the response, so the auth would only work for the specified relay, but the relay wouldn't have the challenge and would deny access.

**Comment by staab** [comment]
Why the downvote? Am I wrong? If relays validate the url in the signed auth message, the relay url can't be spoofed by the proxy.

**Comment by Yonle** [comment]
The fact that you allowed the spoofed value to be signed just make it sounded ridiculous.

**Comment by staab** [comment]
That would be necessary for a proxy to operate. A client might legitimately want to do that if using a trusted proxy.

**Pull request closed without merging**
