### PR TITLE
Rename countries to regions.

### PR DESCRIPTION
**Pull request by ibz**
#461

### CODE REVIEW

**Comment by fiatjaf** [comment]
Looks good to me.

**Comment by motorina0** [comment]
How can we coordinate with other users/interested parties of NIP15?
Chances that they will see this PR are slim.

Are there telegram channels per NIP now? :)

**Comment by ekzyis** [comment]
I think `location` would be better since it's more generic than `region` and `country`. This was mentioned by @ghost here: https://github.com/nostr-protocol/nips/issues/461#issuecomment-1517908873

**Comment by ibz** [comment]
I think `region` is more generic than `location`. You can call Paris a `region` (although it is a small region) but you can't call some bigger region, like France or the EU a `location`. `location` is ways very *local*, hence the name.

**Comment by motorina0** [comment]
> @motorina0 We finally have a Telegram channel for NIP-15! Should I ask there as well?

For whoever might be concerned: 

Channel: https://t.me/+praQQFXCDiFlZGJk

**Pull request merged**
