### PR TITLE
rename "parameterized replaceable event" to "tagged-replaceable event"

### PR DESCRIPTION
**Pull request by fiatjaf**
Because it's impossible to write and takes two minutes to say that other word, "tagged" is nicer. If you have a better name please let me know.

### CODE REVIEW

**Comment by fiatjaf** [comment]
Maybe "addressable event"?

**Comment by alexgleason** [comment]
What does `d` actually stand for?

**Comment by vitorpamplona** [comment]
`tagged` is not that much better. :(

**Comment by patrickReiis** [comment]
What about "**triple** replaceable event"? Considering the fact that a "parameterized replaceable" is a combination of 3 things (pubkey, kind & `d` tag)

**Comment by alexgleason** [comment]
> `tagged` is not that much better. :(

Why not? It's a 7 syllable difference. Ambiguity?

I was thinking d-tagged replaceable event, or even just d-replaceable event. But I still don't know why we use that letter. Maybe we should invent a backronym.

**Comment by arthurfranca** [comment]
> What does d actually stand for?

"d"eduplication id

**Comment by vitorpamplona** [comment]
d-anchored event?

**Comment by fernandolguevara** [comment]
named replaceable event?

**Comment by staab** [comment]
I have an idea, what about "parameterized replaceable event"?

**Pull request closed without merging**
