### PR TITLE
Add DVM kinds to list

### PR DESCRIPTION
**Pull request by AsaiToshiya**

### CODE REVIEW

**Comment by fiatjaf** [comment]
I can't see the changes because of the reformatting.
Can we add just the DVM range?

**Comment by AsaiToshiya** [comment]
@fiatjaf Sure, updated the commit.

**Comment by fiatjaf** [comment]
Oh, I see it now. Thank you.
I was actually just asking you to say what had changed, no need to revert the table formatting.
So it was indeed just the ranges.

**Comment by weex** [comment]
@AsaiToshiya To keep patches minimal, it's better not to change column widths in the source file. Column widths as a display property are better handled by the renderer. If this has been discussed before please disregard.

**Comment by AsaiToshiya** [comment]
@weex Thanks for your advice. I know, but I don't know if that has been discussed before.

**Pull request merged**
