### PR TITLE
NIP-25: Handle empty string as +

### PR DESCRIPTION
**Pull request by benthecarman**
Seems like a bunch of clients assume this so it should be documented

### CODE REVIEW

**Comment by jb55** [comment]
The original spec was like this, not sure why we removed it...

**Comment by alexgleason** [comment]
Why heart and not `+`?

**Comment by benthecarman** [comment]
> Why heart and not `+`?

I am not sure, this is what other clients have implemented so I just want to document it

**Comment by fiatjaf** [comment]
I thought this was the spec already. I mean handling like `+`.

**Comment by benthecarman** [comment]
Changed to `+`

**Comment by vitorpamplona** [comment]
hah... I didn't know that... living and learning.

**Review by jb55 — APPROVED** [review]

**Pull request merged**
