### PR TITLE
NIP-19: add `nchannel` prefix

### PR DESCRIPTION
**Pull request by yukibtc**
Add NIP-19 bech32 prefix for channels.

### CODE REVIEW

**Comment by fiatjaf** [comment]
Nice. Is it implemented somewhere?

**Comment by yukibtc** [comment]
> Nice. Is it implemented somewhere?

I'll implement here: https://github.com/rust-nostr/nostr

**Comment by yukibtc** [comment]
> Nice. Is it implemented somewhere?



> Nice. Is it implemented somewhere?

Do you think that is better to add this prefix in `Shareable identifiers with extra metadata`?
Or leave as I have done?

**Comment by 0xtrr** [comment]
I think it would be good to add an example under the [Examples](https://github.com/nostr-protocol/nips/blob/master/19.md#examples) section in this document as well, just like we have with npub and nsec.

**Comment by yukibtc** [comment]
> I think it would be good to add an example under the [Examples](https://github.com/nostr-protocol/nips/blob/master/19.md#examples) section in this document as well, just like we have with npub and nsec.

Yeah, I'll add an example in the next days

**Comment by vitorpamplona** [comment]
Do we really need semantically different `eventid+relay` schemes? 

Otherwise, we are going to have ndm, nlongformtext, nproduct (NIP-45), etc..

**Comment by fiatjaf** [comment]
Yeah, I think it is better to not have more different prefixes.

**Pull request closed without merging**
