### PR TITLE
Kind 16 generic reposts

### PR DESCRIPTION
**Pull request by fiatjaf**
Solving https://github.com/nostr-protocol/nips/pull/576.

### CODE REVIEW

**Comment by staab** [comment]
Do you mind if I use this for moderating public groups?

**Comment by fiatjaf** [comment]
Why not make a new kind?

**Comment by staab** [comment]
I'm mostly joking, I won't use this because I don't use reposts in Coracle, but I do support nevent embeds, which currently are breaking kind 1's based on your concept of composition being non-interoperable, this PR doesn't solve that.

**Comment by fiatjaf** [comment]
Everybody supports nevent embeds, I don't think they are breaking. I also am not a radical about not having composition, I just think people shouldn't be radical about having full composability.

**Comment by staab** [comment]
Interesting, what is the difference between a re-post and an embed, other than the added context?

**Comment by fiatjaf** [comment]
It's the same. The embed is a quote-repost and vice-versa. That's how Twitter works too. The canonical content of a Twitter quote-repost is just a comment plus a link to the other tweet.

NIP-18 reposts are pure reposts, with no added comments.

**Comment by mikedilger** [comment]
ACK

**Comment by vitorpamplona** [comment]
Can we change the advice to add the event into `.content` for 16? 

```
It SHOULD contain the stringified JSON of the reposted note event for a quick look up.
```

**Comment by vitorpamplona** [comment]
Amethyst v60+ supports this change. Kind 1s will be boosted with kind 6 and everything else with kind 16 and the k tag. All generic boosts are shown in the feed just like kind 6s are.

**Comment by fiatjaf** [comment]
Great. Thanks!

**Comment by fiatjaf** [comment]
> Can we change the advice to add the event into .content for 16?

I've changed this on a separate commit.

**Comment by arthurfranca** [comment]
People will use kind 6 to repost all event kinds and also kind 16 with `k: ["1"]` tag ^_^

**Comment by fiatjaf** [comment]
Do you think?

**Comment by fiatjaf** [comment]
[habla.news](https://habla.news/) has also already stopped sending kind:6 and is sending kind:16 now: https://github.com/verbiricha/habla.news/commit/026b678faa1445a7fe994c49201a1e1dbbb0eea2

**Comment by arthurfranca** [comment]
just kidding xd
I think main clients will follow spec and that's what matters most

**Pull request merged**
