### PR TITLE
34.md:some of the ways

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
id:3dafd7f7f154781fc52d45b9634aab74046cb07145a6d1785e0f9ad47a963b4a

**Comment by RandyMcMillan** [comment]
it is clear that there may be other ways to collaborate using a git+nostr protocol and workflow.

**Comment by RandyMcMillan** [comment]
https://github.com/nostr-protocol/nips/assets/152159/2cd0eb2d-7ccd-4d95-8b27-8e73e3bbbde0

**Comment by AsaiToshiya** [comment]
Ah, this is a PR of the commit created with gnostr, isn't it? I was a little confused.

**Comment by AsaiToshiya** [comment]
@fiatjaf

**Pull request closed without merging**
