### PR TITLE
A proposed recommendation for using 'e' and 'p' tags in nostr clients.

### PR DESCRIPTION
**Pull request by unclebob**
This appears to conform to the conventions used in branle, damus, and more-speech.

### CODE REVIEW

**Review by eskema — COMMENTED** [review]
what happens when it's not a reply but there's a mentioned event?  would't that conflict and look like a direct reply?

**Comment by fiatjaf** [comment]
In my opinion "mentions" should be rendered as replies too, but since other clients may not like that it's probably fine to keep that out of this set of recommendations.

Let's make this a NIP.

**Comment by unclebob** [comment]
NIP-13

**Comment by unclebob** [comment]
Renamed to NIP-10.

**Comment by fiatjaf** [comment]
Could have been 13 too, I'm just assigning numbers based on how I feel them. But 10 it is!

**Comment by fiatjaf** [comment]
@unclebob you think instead of writing `optional` on the other NIPs we should always do ~`mandatory`~?

**Pull request merged**
