### PR TITLE
nip-29: restriction for _id_

### PR DESCRIPTION
**Pull request by kehiy**
I decided to update _id_ details before working on `names` #1484. here are some restrictions added and more details.

### CODE REVIEW

**Comment by ismyhc** [comment]
This is okay, but I don't really like "." as a character for an id.

I would stick with a-z,0-9,-,_

**Comment by kehiy** [comment]
@ismyhc I've updated the details. a-z (case-insensitive), 0-9, - and _. which can support UUID as well.

**Comment by ismyhc** [comment]
> @ismyhc I've updated the details. a-z (case-insensitive), 0-9, - and _. which can support UUID as well.

This works for me.

**Comment by kehiy** [comment]
should we close this?
@fiatjaf @ismyhc

**Comment by staab** [comment]
Yes, I think so, since it conflicts with being able to upgrade unmanaged groups now.

**Comment by kehiy** [comment]
@staab thanks a lot. done.

**Pull request closed without merging**
