### PR TITLE
Add kind Lightning.Pub's kind 21000

### PR DESCRIPTION
**Pull request by capitalistdog**
RPC messages for Lightning Pub

### CODE REVIEW

**Comment by capitalistdog** [comment]
> Can you provide more info about how this kind should be used?

its just for ephemeral classification of a specific application: https://github.com/shocknet/Lightning.Pub/blob/master/proto/autogenerated/client.md

**Comment by vitorpamplona** [comment]
Sure, just add the link like `kind:1971` did :)

**Comment by capitalistdog** [comment]
added

**Comment by fiatjaf** [comment]
What a lazy PR.

**Pull request merged**
