### PR TITLE
Nip46 upgrade part2: remove nip05 and create_account, clarify nostrconnect, cleanup, add nip05 signer metadata

### PR DESCRIPTION
**Pull request by nostrband**
A continuation of https://github.com/nostr-protocol/nips/pull/1545, where we agreed on:

> removing NIP-05, updating nostrconnect:// and moving create_account elsewhere

Also added Overview, shifted signing flow example below request/response format description, added nip05 signer metadata description to appendix, compressed nip89 use for signer discovery.

### CODE REVIEW

**Comment by vitorpamplona** [comment]
Can we clarify what the `get_relays` method does? Where are these relays coming from? the signer service? or the user's NIP-65 relays? Both? Or maybe a hardcoded relay set on the service?

**Comment by nostrband** [comment]
Inviting @mikedilger and @greenart7c3

**Comment by vitorpamplona** [comment]
> so maybe we could deprecate it?

Yeah, delete everything that is not being used.

**Comment by nostrband** [comment]
> Yeah, delete everything that is not being used.

How about `ping`? Anyone using it or at least have the rationale for it?

**Comment by greenart7c3** [comment]
Looks good to me.
ping I never implemented and I don't remember anyone asking for it.
The get_relays doesn't make sense to me, specially in this nip. 

Why would a signer have my nip 65 relays? It would just make things even more complicated for signers since it would need to keep track of user relays and not only the relays from this nip
If it's the relays from the connection them how would the client know if a user replaces relay1 with relay2

**Comment by staab** [comment]
get_relays should return, if anything, relays where the client can immediately find the user's 10002 (and maybe 0, 3, 10050). This could be an indexer, rather than the user's actual relay selections, which would make it easier for a signer to maintain. Also, it's germane to the signer's value prop, because a signer with good relay hints will result in a better sign-in experience. That's not to say that I use these anywhere. I agree with Alex, it's a good idea in theory. Maybe in practice, as the network partitions.

**Comment by nostrband** [comment]
Brought `get_relays` back. I'm not convinced signer can magically find better relays than client itself, but let's discuss it elsewhere.

**Comment by fiatjaf** [comment]
I didn't inspect every line change carefully, but if this is just what it says then I think we should be good to merge, right?

**Comment by mikedilger** [comment]
Overall it looks good to me.

**Comment by manimejia** [comment]
I apologize for busting in on this old thread, but have a couple questions ...
- the spec for 'create_account' method was removed from NIP46, but has NOT been re-specified in another NIP. Is this correct?
- The ephemeral 'client-keypair' (generated and used for each client initiated connection) does NOT allow for persistent storage of user-granted client permissions across sessions. If a user, or client, or remote signer wanted to identify a client and persist permissions across sessions, how should this be accomplished in a standardized manner?

These questions arise from my observation that nsec.app has implemented a rather cumbersome [workaround](https://github.com/nostrband/noauth/blob/main/packages/client/src/pages/CreatePage/Create.Page.tsx#L137) to allow for clients to request remote NSEC generation and permission persistence. BUT their implementation uses nonstandard URL parameters : 'appNpub', 'name', 'perms', and 'redirect_url' IN ADDITION TO the standard 'nostrconnect://' token specified by NIP46. 

To assure robust protection of self sovereignty for end users, it is imperative that client apps (those that modify events prior to signing) DO NOT generate keypairs, and that remote signing apps (those that sign but do NOT otherwise modify events) only generate and store keypairs LOCALLY. Nsec.app is doing everything right, EXCEPT for the fact that their implementation has not been standardized to allow for ANY client to request key generation (and persistent storage of permissions) from ANY remote signer.

I am ready to move forward with (my best shot at) authoring some code and specifications, but wanted to ask these questions and collect any guidance y'all may have.

**Comment by nostrband** [comment]
Nsec.app's appNpub query param is an implementation detail - that's nsec.app's generated url passed as auth_url back to client on 'connect' or other auth-requiring calls, and it always matches the client's pubkey, whichever they pass. If client wants to persist a session key, it's up to them, I don't think there's a way for signer to enforce "one per session" key. 

Nsec.app tries to intelligently group sessions by the url they pass (and assumes referrer as client's url), and suggests to "inherit" permissions from other connections from the same url, that's indeed a workaround, but that's mostly a UX 
necessity if connections are coming across devices - there's no way to pass persistent session across devices unless user manually copies a bunker url. 

Anyway, I'd be happy if some improvements are suggested, but I don't really see any low hanging fruits here.

**Comment by nostrband** [comment]
Wrt create_account, I think an attempt to inject the account creation flow into the RPC was a mistake. Allowing auth_url replies at RPC level allows to interrupt the RPC calls and inject confirmation flows whenever signer needs that. Without an established connection there's no RPC, the connection establishment always requires human action, and injecting it into RPC is just cumbersome mess for no real benefit, and also a spam vector. 

Connection and sign-up are much simpler achieved with bunker-url/nostrconnect strings - either manually copying them, or redirecting from either side to the peer (I've only seen and implemented client-to-signer redirects). Redirect flows are not specified and describing this part would make sense - i.e. signer could announce connect_redirect_url and signup_redirect_url templates in their nip89 event and clients could redirect there and pass their nostrconnect string (that's roughly what nsec.app and nostr-login support).

**Pull request merged**
