### PR TITLE
NIP-9000: AI Assistants

### PR DESCRIPTION
**Pull request by nostal9000**
Submitting a PR for NIP-9000, a protocol to enable public conversations with AI assistants. It covers event types, roles, AI prompt/response mechanisms via a new kinds `9000` and `9001`, and AI bot integration.

Looking forward to your feedback and suggestions.

Inspired by HAL-9000. Co-written with a certain assistente número quatro.

### CODE REVIEW

**Comment by melvincarvalho** [comment]
Cool idea.  Could you say why a new kind is needed, rather than a tag?

We already have AI bots interacting with nostr via kind 1.

**Comment by nostal9000** [comment]
Great question!

Introducing a new kind, rather than using just a tag, brings some key benefits to interactions with AI assistants:

1. Regenerating responses: A new kind allows users to generate multiple AI responses and modify them as needed without cluttering kind 1 messages, keeping conversations easy to follow.
2. Distinct prompt submission: With kind 9000, managing AI prompt submissions becomes more straightforward since it separates them from regular replies.
3. Streaming responses: With kind 9001, AI assistants can stream responses, ensuring a smoother and more dynamic conversation experience.
4. Preserving the authenticity of human conversations: Separating AI-generated content from human interactions helps maintain trust and prevents confusion among users.
5. Preventing AI domination: Ensuring AI assistants don't consume all the energy and vibes of the platform, creating a balanced environment for humans and AI. If a message from an AI assistant resonates with a user, they can copy it over to kind 1.
6. Aligning AI with human values: Easier monitoring and management of AI interactions to ensure they align with human values and positively contribute to the conversation experience.

Distinguishing between human and AI communication protocols is indeed essential for fostering safe AI in the ecosystem.

**Comment by melvincarvalho** [comment]
Makes sense.  So it's like the ChatGPT page / API and operates as a sandbox.  But then maybe the sandbox could also interact with nostr, in another context.  We've noticed with bots that it does generate curiosity in the community the questions and answers.  Though not every interaction will be that way, some more public, some more private.

**Comment by nostal9000** [comment]
Yes, that's a good way to think about it. NIP-9000 is specifically designed to extract value from AI conversations, enabling people to receive compensation for the things that AIs write while maintaining the ability to trace how the AI arrived at its responses. Nostr is an excellent platform for this because it provides a way to offer cryptographic evidence of the prompts and responses. Through Nostr, the community can develop trust in the specific AI personality used to generate the content, which is ultimately controlled by the human holding the private keys that determine the prompts to be queried.

Bots can undoubtedly generate interest and engagement in the community through their interactions, whether those interactions are public or private. However, the success of projects that use NIP-9000 will ultimately depend on their specific use cases and objectives.

**Comment by nostal9000** [comment]
In response to @melvincarvalho's insightful suggestion, we have decided to retain kind 1 for events in our chat app, following our experimentation with the NIP-9000.

We will use kind 90xx for custom types, such as live streaming individual words and establishing bittorrent connections for media sharing. This represents intermediate steps in the communication process between humans and machines.

After reviewing all the conference videos from Nostrica (special thanks to @rockstar for the shoutout), we have gained a deeper understanding of the vital roles that relays play in our network. Accordingly, we will implement:
- Private relays for sandboxing purposes, and
- Public relays to facilitate collaborative conversations.
Additionally, we acknowledge the significance of allowing any client to access AI chats. As a result, we plan to modify the protocol to incorporate these enhancements.

We greatly appreciate the ongoing feedback from the community. We will now close this issue and begin revising the proposal.

**Comment by DiegoADominguez** [comment]
Hi @nostal9000! I saw the bounty on https://bountsr.org/Public-Conversations-with-AI-Assistants/ and was wondering if still available?

Ive built a simple demo of the bounty requirements and would love to show you.

**Pull request closed without merging**
