### PR TITLE
Update tag list

### PR DESCRIPTION
**Pull request by AsaiToshiya**

### CODE REVIEW

**Comment by fiatjaf** [comment]
Is this correct? The relay isn't the tag value, or is it?

**Comment by Egge7** [comment]
> Is this correct? The relay isn't the tag value, or is it?

<pubkey, ?relay, ?weight>

**Comment by AsaiToshiya** [comment]
This is based on changing 5d63b15, but am I wrong?

**Comment by vitorpamplona** [comment]
+1 This is correct.

**Pull request merged**
