### PR TITLE
nip-01.md: kind: 0 - set_metadata conform to a standard event

### PR DESCRIPTION
**Pull request by RandyMcMillan**
added an example

### CODE REVIEW

**Comment by fiatjaf** [comment]
This actually does look good, but we can't do this at this point. The benefits are not worth the cost.

We could however add a recommendation to NIP-01 for future event kinds that need different kinds of metadata to add them as tags instead of as stringified JSON on content.

**Comment by RandyMcMillan** [comment]
Yes detecting a "legacy" and/or an upgraded kind: 0 is reasonable.

**Comment by RandyMcMillan** [comment]
Being able to add an OPENPGP: "<fingerprint>" detection would be an added value - and enable alternate encryption schemes etc...

**Comment by RandyMcMillan** [comment]
@fiatjaf - if you want to post a patch to the wording I will amend the PR.

**Comment by fiatjaf** [comment]
No, what I was saying is that this PR can't be merged.

What is the goal you have in mind for this? Being able to add an openpgp fingerprint to the metadata event? You can do it already today if you want, either in the JSON body or as a tag.

**Comment by RandyMcMillan** [comment]
The OPENPGP mention was just an example use case - the idea is to expand kind: 0 set_metadata to enable additional profile information as well as to simply conform to a standard EVENT. Maybe I am missing something (my apologize). The structure on the set_metadata is unclear. More generally these partial examples in the documentation are a little too terse - they should include example JSON in context of an entire EVENT (some do - but not all). This would clarify a lot for me and other people trying to implement NIPs. Thanks for your patience. NOTE: This is probably why relay implementations are diverging and/or are slow to add support for NIPs.

**Comment by RandyMcMillan** [comment]
This PR was started initially because I attempted to push a set_metadata EVENT to update my profile and it broke my profile metadata. Please post an example of an entire EVENT to do this. Thanks.

**Comment by Cameri** [comment]
@RandyMcMillan Just add that to include extra metadata you must do it in the tags. The content property should not be changed because that would break every single client out there.

**Comment by jb55** [comment]
I closed this since it looks like this stemmed from a misunderstanding about the contents of kind0. feel free to reopen if you feel like it's still worth continuing the discussion.

**Pull request closed without merging**
