### PR TITLE
update NIP-05 addressing reflectivity.

### PR DESCRIPTION
**Pull request by majestrate**
address issue #127

add security constraints to mitigate XSRF properties in NIP-05

### CODE REVIEW

**Comment by gkbrk** [comment]
Are we really asking every domain on the web to add a DNS record to opt out, instead of asking for the comparatively minuscule number of NIP-05 serving domains to opt in?

**Comment by majestrate** [comment]
in general, i find that having to configure another dns record to be the biggest PITA when setting a service up. 

i am okay with opt in, i just thought that an explicit opt out would help with regards to negative caching of dns. e.g. removing the old record but it remains in the cache for a few days.

**Comment by majestrate** [comment]
also, the dns record is out of scope of that issue. it is now omitted.

**Comment by gkbrk** [comment]
Looks good, if clients are recommended to ignore redirects, there would be no point in bad servers trying to do it either.

If someone really wants to delegate Nostr lookups to different servers, they can reverse-proxy the requests instead of using an HTTP Redirect.

**Comment by majestrate** [comment]
>Looks good, if clients are recommended to ignore redirects, there would be no point in bad servers trying to do it either.

this uses RFC 2119 language. MUST is not a recommendation.

**Comment by gkbrk** [comment]
> this uses RFC 2119 language. MUST is not a recommendation.

Haha, I'm sure any client that follows redirects anyway will feel terrible about not listening to RFC-2119 language.

**Comment by majestrate** [comment]
>Haha, I'm sure any client that follows redirects anyway will feel terrible about not listening to RFC-2119 language.

my understanding is that following these redirects is the default behavior on a browser hitting an endpoint with wide open CORS.

**Comment by gkbrk** [comment]
> my understanding is that following these redirects is the default behavior on a browser hitting an endpoint with wide open CORS.

Any decent HTTP client can configure following redirects or not, and the browser is no exception. The `fetch` API can be considered to not follow redirects, or even raise errors if a redirect is asked.

https://developer.mozilla.org/en-US/docs/Web/API/fetch#redirect

**Comment by majestrate** [comment]
> > my understanding is that following these redirects is the default behavior on a browser hitting an endpoint with wide open CORS.
> 
> Any decent HTTP client can configure following redirects or not, and the browser is no exception. The `fetch` API can be considered to not follow redirects, or even raise errors if a redirect is asked.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/fetch#redirect

correct, and a naive implementation will use the default:

```
redirect
How to handle a redirect response:

  follow: Automatically follow redirects. Unless otherwise stated the redirect mode is set to follow.
```

hence the note here about this being explicitly not allowed. the defaults of the fetch api are not going to do that.

**Comment by fiatjaf** [comment]
I think they must not redirect _at all_, not only cross-origin.

**Comment by majestrate** [comment]
updated to disallow all redirects

**Pull request merged**
