### PR TITLE
NIP-55: Add intent flags to open the signer once when sending multiple events

### PR DESCRIPTION
**Pull request by greenart7c3**

### CODE REVIEW

**Comment by greenart7c3** [comment]
@vitorpamplona can you review this?
It was missing asking for multiple signatures in this nip

**Comment by vitorpamplona** [comment]
The guidance seems right. And we are already supporting this, right? This PR just adds information on how to do it correctly.

**Comment by greenart7c3** [comment]
Yes, we already support this

**Comment by vitorpamplona** [comment]
I merged. I am not sure this level of detail should be in the NIP, but we can always remove it later if it becomes too big.

**Comment by dluvian** [comment]
Check spelling before merging :D

**Pull request merged**
