### PR TITLE
Nip10

### PR DESCRIPTION
**Pull request by unclebob**
This is an update to NIP-10 that introduces "marked" "e" tags that help to eliminate the ambiguities in replies.

### CODE REVIEW

**Comment by unclebob** [comment]
This pull request contains the changes to NIP-10 that introduce the marked tag concept.  It also contains NIP-14 that talks about the "subject" tag.

**Comment by fiatjaf** [comment]
Looks good to me!

**Comment by unclebob** [comment]
Roger.  I don't think I can merge it.

**Comment by jb55** [comment]
LGTM

**Pull request merged**
