### PR TITLE
NIP-07: add NIP-44 calls

### PR DESCRIPTION
**Pull request by alexgleason**
Very simpler alternative to #940

It does the same thing as NIP-04 but with the better encryption.

### CODE REVIEW

**Review by staab — APPROVED** [review]

**Comment by staab** [comment]
We've come full circle 😂

**Comment by monlovesmango** [comment]
I won't stand in the way of this if this is what most want. I still do think the batched calls are useful and would be nice to align with NIP46 (especially bc I think NIP46 is the future and NIP07 will become increasingly obsolete, and having them be similar increases support for both).

@alexgleason I am curious what your opinion is on exposing getConversationKey?

**Comment by vitorpamplona** [comment]
We are debating too many hypotheticals. 

Does anybody have a Client implementation that calls NIP-44 methods with arrays? Is there a Signer that takes in and displays the array to the user for approval? If not, then let's merge this. 

If the need for arrays comes up, I am sure we can just add new methods to deal with that need.

**Comment by staab** [comment]
Well, there is this: https://github.com/fiatjaf/nos2x/pull/47/files, but I don't think it's deployed yet. I also used the same approach with alby. But neither is released, I'm just waiting for this discussion to resolve. So yeah, let's just go back to NIP 04 and add bulk options if we need them.

**Review by monlovesmango — APPROVED** [review]

**Comment by fiatjaf** [comment]
What is the argument against having an optional `getConversationKey()` method? I never read that. No one likes that anymore?

**Comment by vitorpamplona** [comment]
The best argument for not needing `getConversationKey` in this PR is that no client needs it yet. :)

**Comment by staab** [comment]
> What is the argument against having an optional getConversationKey() method? I never read that. No one likes that anymore?

You log into `evil client`. It fetches private messages, and asks you for conversation keys for each. As part of that giant wall of alby requests, it also asks for every conversation key for every likely/possible contact, and (if using time-based salt) across every epoch from now until 10 years in the future. Then it stores them on a server. Now it has access to all your messages in perpetuity with any specified counter party, and you have no idea.

**Comment by fiatjaf** [comment]
Fine.

**Comment by staab** [comment]
Updated my PRs to [nos2x](https://github.com/fiatjaf/nos2x/pull/57) and [alby](https://github.com/getAlby/lightning-browser-extension/pull/2653).

**Comment by alexgleason** [comment]
Looks like https://github.com/fiatjaf/nos2x/pull/57 is merged. #983 is merged. Everyone is pretty much in agreement at this point. This should be ready to merge.

**Comment by erskingardner** [comment]
CleanShot 2024-02-22 at 08 26 59

That changeset... a thing of beauty.

**Pull request merged**
