### PR TITLE
NIP-24: Rich Text Note

### PR DESCRIPTION
**Pull request by AsaiToshiya**
This NIP defines kinds for a "rich text note" such as HTML and Markdown that are primarily displayed in "social" clients.

Read [here](https://github.com/AsaiToshiya/nips/blob/nip-24-rich-text-note/24.md).

Related: #589

### CODE REVIEW

**Comment by fiatjaf** [comment]
This is a slippery slope and will for sure cause centralization due to users migrating to clients that support these things over others.

I very strongly ask and recommend that you don't implement this.

**Comment by AsaiToshiya** [comment]
I think I understand your thinking. I would like to hear what the rest of you think.

**Comment by leoperegrino** [comment]
I think HTML is not that hard to implement for webclients.
Markdown is not that trivial, but it could be left to NIP-23 that already uses markdown.
In HTML, Webclients need to do something else besides replace `script` tags?
With so many native js applications, HTML does not seem too bad, no?

**Comment by mikedilger** [comment]
The problem with HTML content is that clients that are not built on web technologies like gossip would need to bundle in a web rendering library which is a gigantic thing with plenty of security implications.  For clients that are built on browser technologies, they would need to apply a lot of scrutiny to be sure there are no security holes.  I'm very much against HTML in nostr.

As for markdown, we have NIP-23.

**Comment by leoperegrino** [comment]
I understand but I'm not sure why is there a NIP for markdown and not one for HTML

**Comment by AsaiToshiya** [comment]
NIP-23 is a parameterized replaceable event. If you think notes are also replaceable, NIP-23 is enough as you say.

**Comment by AsaiToshiya** [comment]
I close this PR in favor of https://github.com/nostr-protocol/nips/pull/619#issuecomment-1604093362 and https://github.com/nostr-protocol/nips/issues/646#issuecomment-1628888642.

If you need HTML, I think you should propose it along with the new use cases that require it.

**Pull request closed without merging**
