### PR TITLE
Nip 121 basic joins

### PR DESCRIPTION
**Pull request by jason19710815**
Hi All... This is a proposal for a simple enhancement that I believe would improve the UX of Nostr apps. It could do this by improving screen load times, reducing the jumpiness of screen elements during the initial load, and preventing the problem of missing content (displaying pubkeys instead of user names and robot heads instead of PFPs).  

While this NIP's implementation would be pretty straightforward for relays using relational or nosql databases, Cameri has raised a question as to how relays using non-relational data stores might implement the NIP and has shared that one of the principles behind the Nostr protocol design is that it remains agnostic in terms of technology used for implementations. This makes perfect sense of course. 

I figured I'd go ahead and submit the NIP for discussion so the community can weigh these pros and cons to see if a path forward can be found. Thanks in advance for considering it and for the opportunity to maybe make a small contribution to the protocol.

### CODE REVIEW

**Comment by staab** [comment]
NACK, joins/relations don't really fit the event-sourcing paradigm. Joins add a lot of complexity by implicitly defining certain kinds of events and new data types. Arguably other features already do this, but still.

**Comment by Egge7** [comment]
NACK. This sounds like offloading tasks to relays that are easily solvable on the client side. Introducing this NIP will also not necessarily reduce complexity on the clients code base, as they would still need to offer fallbacks, to remain compatible with all of the network.

**Comment by jason19710815** [comment]
> NACK. This sounds like offloading tasks to relays that are easily solvable on the client side. Introducing this NIP will also not necessarily reduce complexity on the clients code base, as they would still need to offer fallbacks, to remain compatible with all of the network.

I definitely see the validity in your second point in that the only way to avoid clients needing to offer fallbacks would be to require the NIP on all relays, which is highly unlikely to happen at this stage. 

I would say though, that if the problem were easily solvable by clients, we wouldn't still be seeing pubkeys and robohash pfps popping up on well developed clients like Damus. Not to mention high power devices running hot because they're working so hard. So I think the problem remains unsolved. 

The question is then, what is the solution? If this work remains on the client, then we risk turning off users who expect modern UX and/or alienating those with less powerful devices. Not everybody in the world can afford powerful phones with unlimited data plans and I don't think they should be excluded from Nostr. If we move the work to bespoke backends (the most likely solution for VC funded super apps) that aggregate data and provide querying services, then we risk client and relay centralization. These backends won't emerge out of bad intentions, they'll simply be necessary to provide the best experience for users. For instance, identity on the web was captured because early players found ways to solve a problem unaddressed by the protocol itself. And people and devs gravitated to these providers because they simplified onboarding UX.

This NIP is pragmatic because, like Nostr, it colors outside of the lines a bit to keep the playing field level for all participants. It isn't perfect, but maybe we should keep it in our back pockets. We might see a need for it someday.

**Comment by jason19710815** [comment]
>  NACK, joins/relations don't really fit the event-sourcing paradigm. Joins add a lot of complexity by implicitly defining certain kinds of events and new data types. Arguably other features already do this, but still.

I agree that this would be a whacky idea in any conventional architectural discussion. But so would connecting to a dozen ws services to request a dozen copies of hundreds of the same events. That's what we do though because it serves the purpose of not being reliant on any single source. Nostr also supports mutable events, which is a no-go in most event-driven systems. Point being, Nostr itself doesn't follow a strict event-sourcing paradigm. It is its own paradigm. That being the case, does it make sense to apply conventional constraints to an unconventional protocol? 

You also said that "joins add a lot of complexity by implicitly defining certain kinds of events and new data types..." I take this to mean the shape of the response would change based on if a join was performed. Is that the concern?

Regarding kinds… No new kinds would be introduced by this NIP, implicitly or otherwise.

**Comment by staab** [comment]
Sorry, should have commented on closing. If someone wants to ACK this we can keep talking it over, but my guess is that this won't get much traction from the rest of the community.

**Comment by jason19710815** [comment]
Thanks for the explanation. I see what you mean. Those links could be made explicit, but there's no need to discuss refining a proposal with such little interest. I appreciate your time. :-)

**Comment by staab** [comment]
Reviewing this one more time just to make sure I understood it, it also seems to introduce a new return type? So in other words the return type would use the EVENT verb, but return something other than an event? IOW, the return type can't be signed by the author, because the tags are not what the author signed when publishing.

**Pull request closed without merging**
