### PR TITLE
nip44: clarify ecdh hashing

### PR DESCRIPTION
**Pull request by paulmillr**
Community member wasted time because of that.

### CODE REVIEW

**Comment by staab** [comment]
I don't have the audit in front of me, but I believe it said not hashibg was ok, but it would be better to hash.

**Comment by paulmillr** [comment]
audit https://github.com/paulmillr/nip44/blob/main/audit-2023.12.pdf

I don't think there was anything like that. In any case we don't hash it and we don't plan to.

**Comment by prolic** [comment]
@paulmillr Thanks for the assitance

**Comment by staab** [comment]
Ok, thanks, I skimmed the report as well and didn't see anything.

**Comment by vitorpamplona** [comment]
Ack. I remember having the same question when I was coding and having to look at the raw code to find which one matched what @paulmillr was asking for. Tweak_mul was it. 

That being said, since this error seems common and the secp lib is where people are going to look, I do think the PR could mention the function names to avoid any additional misunderstanding of this. If function names change, we could change the NIP note as well.

**Comment by mikedilger** [comment]
I would change "unnecessary" to "unnecessary and incompatible" to be even more clear.

Other than that,
ACK

**Comment by paulmillr** [comment]
updated

**Review by staab — APPROVED** [review]

**Review by vitorpamplona — APPROVED** [review]

**Comment by prolic** [comment]
ACK

**Review by prolic — APPROVED** [review]

**Pull request merged**
