### PR TITLE
Update 51.md to add support for video lists

### PR DESCRIPTION
**Pull request by zmeyer44**
The thought is to enable users to create playlists or better categorized lists of videos

### CODE REVIEW

**Review by staab — APPROVED** [review]

**Comment by pablof7z** [comment]
Why kind:1 notes?

**Comment by zmeyer44** [comment]
> Why kind:1 notes?

I just did it bc kind 30004 lists had them. But probably not necessary. I'll remove

**Comment by pablof7z** [comment]
I think for 30023 curations it makes sense: a curation of long and short notes.but a curation of videos and short notes is weird imo

**Comment by AsaiToshiya** [comment]
Doesn't it support vertical videos (kind: 34236)?

Just out of curiosity, why was this PR merged? [Video Events](https://github.com/nostr-protocol/nips/pull/923) is not merged yet.

**Pull request merged**
