### PR TITLE
Nip07 - add nip44

### PR DESCRIPTION
**Pull request by monlovesmango**
add nip44 calls to NIP07 spec

https://github.com/monlovesmango/nips/blob/NIP07-Add-nip44/07.md

### CODE REVIEW

**Comment by staab** [comment]
I'm personally against it, I don't think it accomplishes anything that a well-optimized nip 07 extension can't.

**Comment by vitorpamplona** [comment]
Get key should be available on the Android Signer and the NIP-46 Signers. I think we should add to nip-07 just for consistency in case somebody is making a single app that uses any of the 3 signers.

**Comment by pablof7z** [comment]
+1

I'm with @vitorpamplona ; consistency is good and you can drive a truck through "well-optimized nip07 extension" 😅

**Comment by monlovesmango** [comment]
I have reopened this in a new PR (github wasn't letting me reopen this one) https://github.com/nostr-protocol/nips/pull/940

NIP07 updates were removed from NIP44 PR so opening this again to come to agreement on how nip07 should be updated

**Comment by staab** [comment]
I haven't been able to track all the changes to this file and NIP 46 that have been proposed, what's the argument for `getKey`? The downside is that an evil client can exfiltrate conversation keys for all DMs, and since we have no forward secrecy or post-compromise security that gives them access to snoop forever.

**Pull request closed without merging**
