### PR TITLE
Editable Social Notes

### LINKED ISSUE #646: Editing posts
Parameterized replaceable events will allow us to have text notes of kind `30000`. The semantics would be mostly the same as kind 1 (although a good opportunity to clean up anything).

The client would generate a UUID for the post (and preferably encode it to a nicer format such as base62) and add it to the "d" tag. Then notes would be looked up with the author in the pathname, eg `/@:nip05/:d`.

### PR DESCRIPTION
**Pull request by arthurfranca**
Read [here](https://github.com/arthurfranca/nips/blob/social-notes/99.md)

Fix #646

### CODE REVIEW

**Comment by arthurfranca** [comment]
It seems most people aren't interested on editable social notes, so it isn't worth the trouble.

Though the "Publication Date" section may be useful for the [parameterized replaceable event sort order problem](https://github.com/nostr-protocol/nips/issues/663).

Also the "Text Formatting" section may be useful for using ` instead of * and _ from markdown (which some clients use) because [https://stackoverflow.com/questions/tagged/php*](https://stackoverflow.com/questions/tagged/php*) is a valid url but you can't for instance do *This Italic Test https://stackoverflow.com/questions/tagged/php** correctly or even _https://example.com/.well-known/nostr.json?name=__

**Comment by alexgleason** [comment]
I'm definitely interested. I'm porting all my software from Mastodon to Nostr, and if I have to sacrifice features in the move it will make Nostr less appealing to users.

**Comment by fiatjaf** [comment]
This would be a major blow that would remove elegance and simplicity from Nostr and make it more centralized and censurable. Please don't do this.

**Comment by alexgleason** [comment]
One step at a time. Someone will figure out a way to do this that doesn't break everything. I'm in no rush, we're just brainstorming.

**Comment by jb55** [comment]
let's not fragment kind1 just to have editing.

**Comment by arthurfranca** [comment]
I agree paremetrized replaceable event isn't the answer considering kind 1 is already widespread, though it was interesting seeing how it could look like. Diff events referencing kind 1s should be the way.

**Comment by nickjuntilla** [comment]
Why not just have an "update" kind and then reference the original? Then clients can choose to show the most recent update and history?

**Pull request closed without merging**
