### PR TITLE
Add relay list of kind 3 to NIP-24

### PR DESCRIPTION
**Pull request by AsaiToshiya**
A relay list of kind 3 is not written anywhere and is not clear.

Is the relay list unnecessary? Or is it wrong to write in NIP-24?

### CODE REVIEW

**Review by vitorpamplona — APPROVED** [review]
Finally!

**Comment by vitorpamplona** [comment]
We can mark is as deprecated, but there is no reason to not document the reality that is out there.

**Comment by AsaiToshiya** [comment]
I think it is best to document and deprecate the relay list.

**Comment by staab** [comment]
I could get behind that

**Review by staab — APPROVED** [review]

**Review by staab — COMMENTED** [review]
Don't let me stop anyone who wants to merge this, but I still oppose the change at all. The spec isn't the place to clutter things up with random additional information. If it's not standard, it probably shouldn't be here.

https://github.com/nostr-protocol/nips/pull/746#issuecomment-1738255388

**Comment by AsaiToshiya** [comment]
> The spec isn't the place to clutter things up with random additional information. If it's not standard, it probably shouldn't be here.

If you do not merge this PR for this reason, we should remove below:

https://github.com/nostr-protocol/nips/blob/d6f4598ad6d32b46de6444f39339819faab670d5/24.md?plain=1#L20-L25

https://github.com/nostr-protocol/nips/blob/d6f4598ad6d32b46de6444f39339819faab670d5/65.md?plain=1#L28

**Comment by fabianfabian** [comment]
Strongly agree with at least document, and would prefer deprecate too.

**Comment by jb55** [comment]
"should be removed" seems a bit aggressive

**Comment by jb55** [comment]
On Thu, Sep 28, 2023 at 01:01:09PM +0200, William Casarin wrote:
>"should be removed" seems a bit aggressive

This is like saying it's deprecated but its ok to break clients that haven't updated yet. Pretty bad...

**Comment by fiatjaf** [comment]
You're right, I think the text was just copied from the deprecation above. Fixed it in 84f1915cecc10cfca6584eacfbeecb35bddc65f9.

**Comment by AsaiToshiya** [comment]
I prioritized using the same text, but you're right. Thank you for fixing that.

**Pull request merged**
