### PR TITLE
add nip-20: web comments

### PR DESCRIPTION
**Pull request by fiatjaf**
https://github.com/nostr-protocol/nips/blob/9f9a864ce1e1ebfdcfdd4835cd60807440f038e8/20.md

### CODE REVIEW

**Comment by MTG2000** [comment]
Hey @fiatjaf 

I know I might be wrong, but do you think that including the post's url as the filter tag is good long-term wise??

Because although it's not common, but the structure of the urls can changes sometimes.
Maybe they changed the sluggifing function they are using, or changes the routing strucutre...etc

So if they do that, then that will mean all the comments on the old URL won't appear anymore, right??

Unless for example, instead of replacing the r tag value with the new URL, we just add the new URL to it, so now it contains 2 values.

**Comment by MTG2000** [comment]
What I initially thought of was constructing some kind of unique reference for each post without the usage of the url, something like: `r: "<HOST_NAME> <POST_TYPE> <POST_ID>`.
Where hostname will be something like: Github.
Post type will be something like: Story, question, issue, PR...etc.
Post id will be the id of this post in the database, so it will be unique.

Of course the obvious problem with this approach is that how can other clients construct this Identifier for a post they are linking and they only have its URL??

Because although most websites put the id of the post in their url somewhere, but it's not guaranteed to be in a specific section in the url.

**Comment by fiatjaf** [comment]
I know posts URLs can change, but what can we do? In a decentralized system we have to make compromises. If this gets widespread enough people will stop changing URLs of their posts.

If they ever do, again, no problem, we just lose some comments. They can still show the comments in their page by referencing the old URL -- we just lose the niceness of compatibility with other clients _for that specific URL change case_.

Is there a better idea of how to do this?

Maybe the Nostr widget/extension can check for an ID inside a special `<meta>` tag in the page HTML and use that as a reference, but also include the URL?

**Comment by MTG2000** [comment]
Yeah, that makes sense.

I like the idea of a `<meta>` tag that includes the value of the `r` identifier.
And as you said, it can be done together with the URL.
So when a new event is posted, it should contain a tag like `r` with this meta tag value, and another tag like `u` that represents the normalized URL of the page.
`post({
kind: 34,
 "tags": [
    ["r", "<some kind of identifier included in a meta tag>"],
    ["u", "<normalized URL of the page>"]
  ],
})`

This way, when the "Nostr Commenting Extension/Widget" loads on a page, it first checks to see if there is a `meta` tag with some standardized name, & if it find it, it uses it as the filtering tag for queries. And that's great because it means that it will find all the comments posted for this page.
If it doesn't find such a tag for whatever reason, it fallback to the normalized URL of the page and uses it as the tag filter.
Meaning that it will still get the comment, but there might be ones that won't appear if they were posted on a URL before a change. But as you said, that's probably not a big problem.
`
sub({
cb: ()=>{...}
filter: [
{ "#r": "..."},
{"#u": "..."}
]
})
`

**Comment by MTG2000** [comment]
So how should we move forward with this??

**Comment by fiatjaf** [comment]
Yes.

**Comment by MTG2000** [comment]
> Yes.

By "Yes" you mean that we should move with the approach we talked about above?

What are the next steps before starting to use it?

**Comment by fiatjaf** [comment]
Yes.

The best step is rewriting the NIP proposal and  implementing it, in any order.

**Comment by jb55** [comment]
lgtm

**Comment by Cameri** [comment]
I giggled when I saw the event kind number but what's the idea behind a new kind instead of just using kind 1?

Also, I'd prefer we keep the r tag pointing to URLs even if they change. Web clients should look for the permalink if available on the HTML header if it's a web page.

**Comment by fiatjaf** [comment]
Is there such a thing as a permalink HTML header? What is that?

**Comment by Cameri** [comment]
> Is there such a thing as a permalink HTML header? What is that?

They are called canonical actually: `<link rel="canonical" href="https://example.com/dresses/green-dresses" />` these go on the header of HTML pages.

Source: https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls

**Comment by Cameri** [comment]
Better source maybe https://en.m.wikipedia.org/wiki/Canonical_link_element

**Comment by fiatjaf** [comment]
@MTG2000 I came to the realization that the approach used by @jb55 in https://damus.io/log/ is much better than what we have here in this proposal.

I didn't know how he was doing it, but I went to inspect and he just publishes an event with a link to the blog post and then uses that "foundational" event id to fetch comments as kind-1 events.

It is great because
  1. all kind-1 clients are immediately compatible;
  2. no one loses context because they are replying to a note that has the context already;
  3. the blog post can change URLs and that doesn't matter since the blog can redirect from the original URL which is in the event;
  4. in the awful case in which the blog cannot redirect, you can issue a new event with a new URL for the blog post, and then on the website you can aggregate replies from the two events.

The only addition I would make is to maybe include the blog post URL as a tag in the "foundational" event, so it can be found by other clients if they know they are looking for comments to a specific blog post.

What do you think?

**Comment by MTG2000** [comment]
By "foundational" event, you mean something like an empty event that gets published when the blog post is first published. 
It might be empty (or contains the URL as you suggested).
And is considered as a representation for the post on the Nostr network.

So when you want to query comments, instead of constructing a custom identifier, we can just simply use the #e of the post "foundational" event.

Did I understand that right??

**Comment by fiatjaf** [comment]
Yes, exactly that.

Look at this event used in the Damus blog: https://nostr.com/e/4e8b44bb43018f79bd3efcdcd71af43814cdf996e0c62adedda1ac33bf5e1371

**Comment by jb55** [comment]
in theory you don't even need to publish an event. it could be a random id that all replies reference, so that each one gets picked up in the `#e` query.

**Comment by jb55** [comment]
although I like having it as a real event since it adds context for people who see the replies on the nostr side

**Comment by fiatjaf** [comment]
I think publishing an event is crucial because of the context.

**Comment by MTG2000** [comment]
I see.
It's a nice idea indeed.

Especially because the compatiblity point, and most importantly as you mentioned, the context is kept withing this foundational event, instead of the event object.


Just a few points to consider:

1- How will a comments client/extension running on a post page figure this event id out??

Maybe when the post is created, and the event for it is published to nostr, then this event id is stored together with the rest of the post info in the database, and when displayed in a webpage, this event id is put in a `<meta>` tag as we previously suggested.
Or do you think there could be a better/easier way??


--------------

2- How will external clients that wants to show the comments of some post figure this event id out??

(Not very sure yet...)

--------------

3- Should we use use the `#e` tag to reference the post this comment object belongs to??

Because the `#e` tag is also used to mark the reply to an event (which is also a comment).
So maybe we should go for a different tag like `#r` to reference this foundational event in a comment or reply, and keep the `#e` to mark the reply parent.

--------------

4- Finally, who should be the one responsible for creating this event??

Is it for example the backend api that do that automatically each time a new post is created with it?
Or should it be done by someone other than the api?

**Comment by fiatjaf** [comment]
1. Yes, let's define a `<meta>` tag to put this in. Maybe that one @Cameri mentioned.
2. The foundational event can have an `r` tag with the post URL and clients can use that to query the event, then query its replies, OR they can load the webpage, get the event ID from the meta tag and use that.
3. I think we can all assume very safely that the comments referencing these special events are comments to the webpage, not to the event that references the webpage. This is just common sense.
4. The webpage owner can create it in any way they want and then put it in the meta tag of the webpage.

**Comment by fiatjaf** [comment]
As far as I know all the clients also reference the event at the top of the thread when creating a reply event, not only the immediate event before them.

**Comment by MTG2000** [comment]
Okay, makes sense.
So replies should have 2 `e` tag values, the foundational event id & the reply to object id.

Should we use the `#e` tag value that refers to the foundation event as is, or should we suggest a convention similar to the one for the replies?
i.e `["e", <event-id> <marker=page>]`

Aside from that, any other cases/points that we should think about further ?? 

Or should we start re-writing this NIP according to the newly discussed ideas above?

**Comment by fiatjaf** [comment]
No, just use the `e` tag as normal, for maximum compatibility.

I think we don't even need a NIP. Let's just experiment with it like the Damus blog is doing, then later we write the NIP to just standardize the conventions.

**Comment by MTG2000** [comment]
Gotcha
Yeah, I thought too that we might not need to write a nip this way.

Let's try it this way and see how things will go.

**Comment by MTG2000** [comment]
Hey guys @fiatjaf @jb55 @Cameri 

We are going to be rebuilding our commenting feature from scratch using the new specs above very shortly.

We did some design sprints & discussions internally regarding the implementation & some UX decisions.

And we just wanted to share how we are planning to do it with you guys, in case someone would like to suggest doing something in a different or a better way.

We wrote them as a 4-parts posts series on bolt fun, & you can find'em here:

Part 0 (What is the problem):
https://makers.bolt.fun/story/refactoring-boltfun-nostr-powerd-commenting-feature-part-0--553

Part 1 (What is the required solution):
https://makers.bolt.fun/story/refactoring-boltfun-nostr-powered-commenting-feature-part-1--555

Part 2 (How it will be implemented (1)):
https://makers.bolt.fun/story/refactoring-boltfun-nostr-powered-commenting-feature-part-2--556

Part 3 (How it will be implemented (2)):
https://makers.bolt.fun/story/refactoring-boltfun-nostr-powered-commenting-feature-part-3--557 

There are a couple of UX challenges that we've come across regarding the UX, & we're still not sure about the best way to approach them, so any help or suggestions there are greatly appreciated.

Thanks.

**Comment by fiatjaf** [comment]
Don't do that, @MTG2000!

Message me on t.me/fiatjaf.

I will update this NIP proposal to reflect what I did on https://fiatjaf.com/nostr.html, which I think is the optimal solution.

With regards to the mobile flow, it indeed is tricky, but it is partially solved by the approach above. Would be nice to chat about it.

**Comment by MTG2000** [comment]
Hey guys

So for the past couple of weeks, we've been working on rebuilding bolt.fun's commenting feature from scratch.

We had a few goals in mind for this initial version:
- Following the specs that we discussed here.
- Compatiable with any other nostr-client
- Provides non-custodial option
- As good UX as possible

We finished the development of this initial version just recently, but we haven't released it on production yet, it's now in 'preview stage'.

So I'd greatly appreciate it if you were to take a quick look at the results & see if there is any things we are missing/things we are doing wrong/...etc that you think we should change.

You can check the preview website here: 
https://deploy-preview-229--makers-bolt-fun-preview.netlify.app/story/a-story-to-test-nostr-comments-feature--20

A few points you may wanna know:
- We are doing almost everything client-side.
The only thing done server-side is publishing the "root event" that represents a newly created story when it's created.
Whenever a new story is created, there will be a job on the server to publish an event for it.

- For old stories (where there is no root event), we are using a falling back on using a simple "#r" reference like the initial suggestion at the beggining of this thread.

- We are trying to be as platform-independant as possible, to hopefully make this component easily pluggable on any other web app.
(It's not that easily pluggable right now, the API needs a lot of cleaning, but there is almost no platform-dependence)

- If you'd like to check the code, you can see this component & all the nostr logic here in this folder:
https://github.com/peakshift/makers.bolt.fun/tree/refactor/nostr-commenting-feature/src/features/Posts/Components/Comments/CommentsWidget

It should be clean for the most parts.
(And I reused a lot of the functions & logic from @fiatjaf  nocomment repo: https://github.com/fiatjaf/nocomment, it helped a lot 🙏) 


And that's everything.
So any feedback is greatly appreciated.

**Comment by fiatjaf** [comment]
Looks very good to me. Working great!

The only thing I think you should add (that nocomment doesn't have either, but I'll add) is `nostr:` links to the notes themselves. Oh, nocomment also doesn't have a way to comment on threads, I must fix that.

**Comment by MTG2000** [comment]
Glad to hear that!

Yeah, good point.
I should add the note's link to the card.

**Pull request closed without merging**
