### PR TITLE
add contributors in README.md

### PR DESCRIPTION
**Pull request by vincivermeer**
Hello everyone!

I added the contributors in the readme.md file in the repository: nostr-protocol/nips. I would like to contribute to this pull-request and I hope you all accept it.

what do you all think of this idea?
image

### CODE REVIEW

**Comment by Egge7** [comment]
Feels like unnecessary bloat and adds a third party dependency to the repository. While I truely believe that there should be a place that honors contributors, this repo shouldnt be it IMHO. IT should be about ideas not individuals.

**Comment by vincivermeer** [comment]
Hi Egge7.

> Feels like unnecessary bloat and adds a third party dependency to the repository. While I truely believe that there should be a place that honors contributors, this repo shouldnt be it IMHO. IT should be about ideas not individuals.

- This is my first pull-request. And I would be happy to help. 
- So, I would like to list all nostr contributors in a public and accessible way within the README.md

**Comment by Egge7** [comment]
> - This is my first pull-request. And I would be happy to help. 
> 
> - So, I would like to list all nostr contributors in a public and accessible way within the README.md

Appreciate it and congrats on your first PR. However this does not add any value IMO and it introduces a third party that you rely on. git keeps track of all contributors automatically, so there really is no need for a visual representation in the readme.

**Comment by vincivermeer** [comment]
Hi Egge7.

> Appreciate it and congrats on your first PR. However this does not add any value IMO and it introduces a third party that you rely on. git keeps track of all contributors automatically, so there really is no need for a visual representation in the readme.

close this pull-request, please.

**Comment by fiatjaf** [comment]
Looks like we're talking to an AI here.

**Pull request closed without merging**
