### PR TITLE
NIP-25 content might be NIP-30 custom emoji

### PR DESCRIPTION
**Pull request by mattn**
The content for reactions might be NIP-30 custom emoji.

### CODE REVIEW

**Comment by alexgleason** [comment]
Would it include the colons, eg `:blobcat:`?

**Comment by mattn** [comment]
Yes, I assume it to be `:shortcode:`.

**Comment by alexgleason** [comment]
I that should be clarified. Also, it means an "emoji" tag will also need to be included on the event.

Have you thought about simply including the URL in the content, without the shortcode? What are the pros and cons of that?

**Comment by alexgleason** [comment]
cc @jb55, custom emoji reactions on kind 7

**Comment by mattn** [comment]
I think the emoji tag has future extensibility. For example, it might be possible to put something in the 4th element of array that can be used to decorate the emoji. This has the advantage that the information can be used from the content, I think.

**Comment by alexgleason** [comment]
Okay, after thinking I support this idea. Here's my reasoning:

1. Custom reactions should not be a new kind. They should be kind 7 so they get tallied with COUNT, and unsupported clients should just drop them as they already do with invalid kind 7s.
2. I support using the "emoji" tag so the emoji definition could be extended in the future.
3. It _could_ be a new NIP instead of adding onto NIP-25, but I don't see any benefit to that since relays shouldn't care about the content of kind 7 events(?), so there's no benefit to the supported_nips field.

I do think this needs a separate section in NIP-25 with a headline like "Custom emoji reactions" with a more in-depth explanation and example event.

**Comment by alexgleason** [comment]
Side-note that custom emoji reactions are already supported and working on the Fediverse, so this is not exactly uncharted territory.

**Comment by mattn** [comment]
Added new section Custom Emoji Reaction.

**Comment by alexgleason** [comment]
Can someone else review this? @jb55 @fiatjaf @staab

**Comment by jb55** [comment]
On Mon, Jul 10, 2023 at 08:43:39AM -0700, Alex Gleason wrote:
>Can someone else review this? @jb55 @fiatjaf @staab

I think this is fine.

**Comment by vitorpamplona** [comment]
Yep, looks fine to me too.

**Comment by fiatjaf** [comment]
I hate emojis.

**Pull request merged**
