### PR TITLE
Create NIP for mail events

### PR DESCRIPTION
**Pull request by arejula27**
I write this NIP for creating a new kind of structure direct message as i was suggested in the  issue #83 . I make this proposal for discuss the best way of doing this structured events

### CODE REVIEW

**Comment by eskema** [comment]
so the only difference with nip4 is the encrypted subject?

**Comment by arejula27** [comment]
yes

**Comment by eskema** [comment]
we already have a subject tag, why not simply add that but encrypted like the content, then you decrypt both, you don't need the structure..

**Comment by arejula27** [comment]
The problem is that chat apps will show mail messages and the mail clients  wills how chat mssages. I feel that they are not the same, but if it is what i should do i will do it.

**Comment by eskema** [comment]
> The problem is that chat apps will show mail messages and the mail clients wills how chat mssages. I feel that they are not the same, but if it is what i should do i will do it.

why are they not the same? what's the difference other than the UI abstraction?

**Comment by arejula27** [comment]
for me these messages has not the same context, i dont want to receive on my gmail small messages as good morning, how are you etc. For that u use whatsapp or signal. A mail is used in other context, more polites maybe. For me is more than just a UI asbtraction, is a way of comunication, if they were the same people would just use gmail as a message app.

**Comment by arejula27** [comment]
Another option will be have keys for chat apps and keys for mail apps, maybe it a bit annoying for users idk. What do u think?

**Comment by eskema** [comment]
> for me these messages has not the same context, i dont want to receive on my gmail small messages as good morning, how are you etc. For that u use whatsapp or signal. A mail is used in other context, more polites maybe. For me is more than just a UI asbtraction, is a way of comunication, if they were the same people would just use gmail as a message app.

what prevents anyone from sending you events iun this format but like it was a chat? the format doesn't change anything if it doesn't impose a structure, you can also receive a bunch of these saying `hello sir`

**Comment by arejula27** [comment]
Ofc the format didnt change anything, that the reason i ask for an extension of the nip 5. For setting the intention of the messages. People can send small mail for saying `hello sir` but they dont use to, the prefer other ways, thats the idea. Dont make a mess of messages with different scopes.

**Comment by arejula27** [comment]
The main difference is not the structre, is the intention and the scope of the message, it is not a tech dif, is a language context diff.

**Comment by eskema** [comment]
kind-4 already goes out of the way and makes it a direct communication avenue, it's exactly what you want. the intention is irrelevant if sending a kind-4 or kind-44 if the rest in unchanged, but that's just my perspective, feel free to use a different kind for that, but the key points of nostr is interoperability, so you can levarage existing apps that already talk the same language, if you're creating a new kind just for yourself, you can, but what would be the readon for anyoine else to use your different format if they can already talk to each other?

**Comment by arejula27** [comment]
Sure, i understand your point and see the advantages of it. We can let this pr open for a week to see more peolpe opinions and then we can close it.

**Comment by arejula27** [comment]
I will also ask on anigma, but i thinking your point is really good

**Comment by arejula27** [comment]
I make some updates on the nip, i think now is different from the dm, cuz it has more functionalities (set category, mark if read, etc) If someone want to add something will be helpful.

**Comment by arejula27** [comment]
Im also valuing using shared secrets  #59. The idea would be have a shared secret or group chat as mail thread, but maybe a user will have a lot of keys to manage.

**Comment by jb55** [comment]
something I've always wanted is a more general nip04 that has encrypted tags and maybe even encrypted kinds. you could even retain queryability by hashing the shared secret into the tag value: {kinds: [444], #k: sha256(shared_secret, 7)}  that way you could create reactions to dms, etc.

**Comment by arejula27** [comment]
I like the idea

**Comment by fiatjaf** [comment]
Maybe add email-specific metadata (`subject`, for example) as a tag, then your email client will only show messages containing that?

**Comment by arejula27** [comment]
That was mi initial idea with issue #83, I propose to set a few tags for specifying some kind of encrypted messages. I explained the idea  bad :(

**Comment by jb55** [comment]
> something I've always wanted is a more general nip04 that has encrypted tags and maybe even encrypted kinds. you could even retain queryability by hashing the shared secret into the tag value: {kinds: [444], #k: sha256(shared_secret, 7)} that way you could create reactions to dms, etc.

even more general: 

  `{kinds:[444], #g: [sha256(shared_secret + "kinds" + 4), sha256(shared_secret + "#p" + "pubkey")]}`

but this doesn't work because it is eqivalent to `[REQ,"",{#p: pubkey}, {kinds: [4]}]`, which is an OR query and not what we want. It would be nice if we had a way to do AND in generic tag queries.

**Comment by jb55** [comment]
waiting for @Semisol to take this idea https://github.com/nostr-protocol/nips/pull/84#issuecomment-1332799070 and make it work

**Comment by arejula27** [comment]
I think I will be implement the client as kind 4, cuz every one looks agree with that. 
 @Cameri the pubkey on the content is redundant, there is a reason for it or just following the format? Do you think is convenient?

**Pull request closed without merging**
