### PR TITLE
NIP-60 - Secure file load from URL

### PR DESCRIPTION
**Pull request by leandro21b**
This `NIP` allows images, videos, audios, source codes, etc. to be loaded more securely by `clients` and allows these files to be stored on several servers at the same time.

### CODE REVIEW

**Comment by Egge7** [comment]
How exactly does this allow a file to be loaded more securely, if a client has to load the file in order to then verify the hash?

**Comment by leandro21b** [comment]
The idea of hash verification is to guarantee that the file that someone sees is the same one that was sent, when someone wants to publish an image for example, before the file is sent to the servers, the client generates a hash of that file, later if the server try to change this file will give error in the hash and the client of the user who is seeing this image for example can warn him about this, this increases security and reduces the risk of data manipulation.

**Comment by arthurfranca** [comment]
This is already proposed at [NIP-94](https://github.com/nostr-protocol/nips/pull/337)

**Comment by leandro21b** [comment]
Interesting, also because it can be integrated with the `BitTorrent` protocol, but does it also support several `HTTP` Urls to load a file? Actually this is my main idea with `NIP-60`, because today to load an image via http you depend on a centralized server, hash verification is a way to prevent some of these servers from changing the file that was published, I think that the name `SecurefileloadfromURL` isn't even appropriate to describe my idea, as I didn't focus the name on Decentralization of storage.

**Comment by arthurfranca** [comment]
> [...] but does it also support several HTTP Urls to load a file? [...]

Sure, just add many url tags instead of one.

**Comment by leandro21b** [comment]
Got it, very interesting this `NIP-94`

**Comment by leandro21b** [comment]
Attention: As the main idea of `NIP-60` already exists in `NIP-94` and as I already had another open PR `NIP-53` that I had to close to open this one because both are from the `master branch` of my fork and Github does not allow the 2 PR at the same time from the same branch I am closing this one, if I need to reopen this PR I will have to open another `PR NIP-60` unless there is a way to have 2 PR from the same branch, I apologize for the confusion is that I I'm still learning how to use Github

**Comment by mikedilger** [comment]
@leandro21b Yes put each PR on a separate branch.

@authorfranca this PR isn't the same as NIP-94 which is only a file. This PR is for content referenced from text notes. They are related and should probably be sychronized to use very similar mechanisms, but I think @leandro21b's idea is separate, important and should not be lost.  Unless kind-1 events are supposed to point to kind-1063 events instead of to the content directly, but if so that has not been NIPped anywhere AFAIK.  If I'm talking crazy just let me know, I'm sleepy.

**Comment by arthurfranca** [comment]
@mikedilger yes this PR is an alternative way of referencing media with metadata on kind 1 notes using new tags. But I think we shouldn't introduce a new form of referencing things on text notes.

If all goes well with #381 (NIP-27) and NIP-94 (file metadata, not the file data itself), one could instead reference inline (inside .content) the NIP-94 event id when on text notes, without tags. Also, one could reference inline the http url directly (instead of NIP-94 event) if it doesn't need media metadata.

**Pull request closed without merging**
