### PR TITLE
README: add NIP-73 `k` tag

### PR DESCRIPTION
**Pull request by AsaiToshiya**

### CODE REVIEW

**Comment by staab** [comment]
Shouldn't this be added to the NIPs list on the previous line?

**Comment by AsaiToshiya** [comment]
I thought that "kind number" and "external content" have slightly different meanings, but your thoughts make sense. How is this?

**Comment by staab** [comment]
Looks good, would you mind resolving conflicts, and then I can merge.

**Comment by AsaiToshiya** [comment]
@staab Thanks for review and merge.

**Pull request merged**
