### PR TITLE
NIP-49 [breaking]: password normalized to unicode NFKC format

### PR DESCRIPTION
**Pull request by mikedilger**
This will aid compatibility.

Shocking for me to suggest a breaking change after my hissy fit last night. But I'm actually ok with important breaking changes as long as we document them (see my other PR here https://github.com/nostr-protocol/nips/pull/1052).

### CODE REVIEW

**Comment by vitorpamplona** [comment]
ACK. 

Welcome to the club of NIP breakers.

**Comment by vitorpamplona** [comment]
Good to go from here: https://github.com/vitorpamplona/amethyst/commit/6553f3bec5e43446ace0a6221407e898e9d65d69

**Comment by mikedilger** [comment]
So I would have chosen NFKC from the outset (and this PR is currently written with NFKC) if this had never been deployed, but maybe NFC is better since this is a breaking change and NFC will break less sitautions. NFC only changes things to their canonical form and doesn't fold distinct variants into simpler variants.

Anybody else have an opinion on that?
https://www.unicode.org/reports/tr15/

**Comment by vitorpamplona** [comment]
NFKC is ok for me.

**Comment by fiatjaf** [comment]
Nostr is a shit show.

**Comment by fiatjaf** [comment]
Can we get at least one test vector?

**Comment by mikedilger** [comment]
What language? Kotlin? Go? JavaScript?

**Comment by fiatjaf** [comment]
Go, but I was reading about it and this normalization stuff is used for a bunch of different things, like turning `á` into `a`? Anyway, I think I can figure it out with with some test vectors.

**Comment by mikedilger** [comment]
I am working on test vectors.

**Comment by mikedilger** [comment]
Here is a starting point test vector.  If someone enters the first password below (I've listed it on 3 lines in 3 different ways) the NFKC algorithm should convert it into the second password below (again listed on 3 lines in 3 different ways)

"ÅΩ"
U+212B U+2126
UTF-8 bytes: [0xE2, 0x84, 0xAB 0xE2, 0x84, 0xA6]

"ÅΩ"
U+00C5 U+03A9
UTF-8 bytes: [0xC3 0x85, 0xCE, 0xA9]

**Pull request merged**
