### PR TITLE
Kind mute sets

### LINKED ISSUE #1156: Mute by kind
It would be nice to be able to mute particular pubkey's kind like "mute retweets" in X (Twitter).

- Reposts (kind 6, 16)
- Reactions (kind 7)
- Zaps (kind 9735)
- etc

### JSON

Based on [NIP-51](51.md) sets.

```json
{
  "kind": 30007,
  "content": "<encrypted tags>",
  "tags": [
    ["d", "<kind>"],
    ["p", "<pubkey 1>"],
    ["p", "<pubkey 2>"]
  ]
}
```

### Tags

- `d` (MUST): kind string
- `p`s (MAY): pubkeys
  - Same as kind 10000

### PR DESCRIPTION
**Pull request by SnowCait**
Fix #1156

### JSON Example

```json
{
  "kind": 30007,
  "content": "<encrypted tags>",
  "tags": [
    ["d", "<kind>"],
    ["p", "<pubkey 1>"],
    ["p", "<pubkey 2>"]
  ]
}
```

### CODE REVIEW

**Review by fiatjaf — APPROVED** [review]

**Comment by AsaiToshiya** [comment]
+1. 

I feel like it is more generic mute list than the sets. How about using the `k` tag after all?

**Comment by SnowCait** [comment]
Adding both `k` tag and `p` tag to kind 10000 makes it complex and will breaks existing clients.

Expanding `k` tag to be able to contain pubkey would cause conflicts between NIPs in the future. (It may be okay if the `k` tag has a different meaning for each NIP, but I don't like it.)

**Comment by AsaiToshiya** [comment]
It was not communicated properly. What I want to say is this: 

```json
{
  "kind": 30007,
  "content": "<encrypted tags>",
  "tags": [
    ["d", "<identifier>"],
    ["k", "<kind>"],
    ["p", "<pubkey 1>"],
    ["p", "<pubkey 2>"]
  ]
}
```

How about using the `k` tag like this? Without the `k` tag, it just looks like a generic mute list, not the sets.

**Comment by SnowCait** [comment]
I see.

If `<identifier>` is free input, multiple events will be created for a kind.
It makes clients complex to use kind mute sets.

If `<identifier>` is same as `<kind>`, please see #1156 discussion and edit history.

**Review by AsaiToshiya — APPROVED** [review]
Ok, I guess I didn't understand Alex's comment correctly.

**Comment by SnowCait** [comment]
Implemented in [nostter](https://github.com/SnowCait/nostter) and [lumilumi](https://github.com/TsukemonoGit/lumilumi).

**Pull request merged**
