### PR TITLE
remove NIP-52 label cruft

### PR DESCRIPTION
**Pull request by fiatjaf**
This is a breaking change, but I hope everybody sees how simpler (and cheaper) things are when we remove these unnecessary label and think it's worthwhile to make the required adjustments.

If you think it's not worth the trouble, then at least let's not repeat this mistake in future standards.

### CODE REVIEW

**Comment by fiatjaf** [comment]
@tyiu @zmeyer44

**Review by tyiu — APPROVED** [review]
Looks good to me. I'm fine with making it simpler like this.

The original draft of NIP-52 had these fields as `t` tags so that they would be indexable (as all single letter tags are), in which the feedback was that it'd be better to use labels then (to not confuse with actual hashtags). Yet, the labels approach felt cumbersome for this use case.

In practice, using labels may be overthinking use cases when they haven't presented themselves yet. I'm fine moving forward with the `status` and `fb` labels.

**Comment by vitorpamplona** [comment]
Looks better. I think the namespace + label pair only makes sense when users are defining their own terms.

**Comment by zmeyer44** [comment]
I'd down with these changes. Updating flockstr now

**Comment by Sebastix** [comment]
@zmeyer44 Is flockstr updated? I still see published kind `31923` events with labels and not with the `status` tag.

**Pull request merged**
